[WIP] EntitySource implementation for the v1 registry client
operator-framework/deppy pull request #84
Opened 2023-01-17 18:17 UTC by ankitathomas

An implementation of a RegistryEntitySource that watches CatalogSources on all namespaces. It maintains an internal cache 

See https://github.com/operator-framework/deppy/issues/76

2023-01-17 18:41 UTC, tmshort commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +func (r *CachedRegistryEntitySource) imageIDFromCatalogSource(ctx context.Context, catalogSource *v1alpha1.CatalogSource) string {
Possibly return an `error` from this function, in addition to a `string`? Might make error handling easier, especially since you're collecting an array of errors.

2023-01-18 10:19 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +	r.done <- struct{}{}
you should simply `close(r.done)`. That should be sufficient to trigger any `select case <-r.done: statement` ^^

2023-01-18 10:21 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_bundle_to_entity.go
> +		property.TypePackage:     {},
Are we missing `TypePackageRequired`?

2023-01-18 10:25 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +	r.Mutex.Lock()
I think you should use a RWLock and when reading the cache use RLock. You can have many RLocks, but only one (RW)Lock.

2023-01-19 11:00 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_bundle_to_entity.go
> +		property.TypePackage:     {},
Oh, another thing that came to mind, we also need to know the default channel for the package of the bundle. This important for when we sort the bundles. When no channel is specified, we'd give priority to the default channel.

2023-02-14 05:29 UTC, ankitathomas commented on pkg/deppy/input/catalogsource/registry_bundle_to_entity.go
> +		property.TypePackage:     {},
Added both, we should now have access to both.

2023-02-17 14:02 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_bundle_to_entity.go
> +func entityFromBundle(catsrcID string, bundle *catalogsourceapi.Bundle) (*input.Entity, error) {
it might make sense to break this function down into sub-functions to make it a bit smaller and more readable. You may also want to make a type declaration for the key of the property map, e.g. `type NamespacedName string` or some such.

2023-02-17 14:22 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_grpc_client.go
> +type RegistryClient interface {
can't we straight up use the registry client coming from operator-registry?

2023-02-17 14:25 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_grpc_client.go
> +type RegistryClient interface {
oh nvm - we do

2023-02-23 10:54 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_bundle_to_entity.go
> +	for _, prvAPI := range bundle.ProvidedApis {
It might be good to break these steps into their own functions to make this function a bit smaller and more readable. wdyt?

2023-02-23 10:55 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_bundle_to_entity.go
> +	entityIDFromBundle := func(catsrcID string, bundle *catalogsourceapi.Bundle) deppy.Identifier {
should we just push this out into a proper function rather than an inline one?

2023-02-23 10:56 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +func NewCachedRegistryQuerier(client client.WithWatch, rClient RegistryClient, logger *logr.Logger, options ...Option) *CachedRegistryEntitySource {
could the registry client be internal to this struct?

2023-02-23 10:57 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +func NewCachedRegistryQuerier(client client.WithWatch, rClient RegistryClient, logger *logr.Logger, options ...Option) *CachedRegistryEntitySource {
might also be worth adding the logger as an option with `zap.New()` as the default value.
if you want to allow for custom registry client implementations, it might also be worth moving this to an option and using yours as the default.

2023-02-23 11:01 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +func (r *CachedRegistryEntitySource) Get(ctx context.Context, id deppy.Identifier) *input.Entity {
rather than iterating over the whole cache to find the item, could you break out the catalog source component of the key and go directly to the right map?

2023-02-23 11:02 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +func (r *CachedRegistryEntitySource) Filter(ctx context.Context, filter input.Predicate) (input.EntityList, error) {
you could re-use `Iterate` here to reduce /reuse some of the code

2023-02-23 11:03 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +func (r *CachedRegistryEntitySource) GroupBy(ctx context.Context, fn input.GroupByFunction) (input.EntityListMap, error) {
same here - you could re-use `Iterate`

2023-02-23 11:14 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +				func() {
I'd say move this to its own function, wdyt?

2023-02-23 11:15 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +			encodedObj, err := json.Marshal(entry.Object)
another option might to be just cast it to a `*v1alpha1.CatalogSource`, e.g.
```
catalogsource, ok := entry.Object.(*v1alpha1.CatalogSource)
```

2023-02-23 11:17 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +	for {
might be worth wrapping this into its own function and using adding `defer r.Stop()` + any other shutdown bits

2023-02-23 11:18 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +					catalogSourceKey := types.NamespacedName{Namespace: catalogSource.Namespace, Name: catalogSource.Name}
maybe push this to its own function. I think I've seen it around a couple of times in the code

2023-02-23 11:23 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +				r.syncCatalogSource(ctx, catalogSource)
we should consider using the workqueue to drive sync in a different go routine. When something is added or modified add that resource to the workqueue. This could also help us with error handling and retries. E.g. if there's a connection failure or transient issue, we can just re-enqueue the resource after some time.

careful with modified because it can happen frequently - e.g. everytime the connection state changes - we should only trigger a resync for certain changes to the resource. Maybe when the connection state is READY?

2023-02-23 12:19 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +			r.syncCatalogSource(ctx, catalogSource)
we should catch any errors here and re-enqueue the catalog if it they happen. We may want to understand how this work queue works so we can have an exponential backoff. It may also be worth emitting a kube event that says that the cache couldn't be sync'ed for a particular catalog and that it will retry in so many seconds.

2023-02-23 12:19 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +		//imageID: imageID,
is this comment still valid?

2023-02-23 12:21 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +	r.cache[catalogSourceKey.String()] = sourceCache{
nice - change the whole entry at once - makes it atomic ^^

2023-02-23 12:22 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier.go
> +	sync.RWMutex
how come this is exported rather than an internal variable? is this a Go pattern?

2023-02-23 12:23 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_grpc_client.go
> +	if conn != nil {
nit: you could change this to

```
if err != nil {
  return ...
}
defer conn.Close()
```

2023-02-23 12:25 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_grpc_client.go
> +		entity, err := EntityFromBundle(catalogSourceID, pkg, bundle)
since this function is in the same package we can get away with not exporting it - or did you export it to make testing easier?

2023-02-23 12:26 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_grpc_client.go
> +			return entities, fmt.Errorf("failed to parse entity %s: %v", entity.Identifier(), err)
do you mean to return partial results? it might be worth just returning nil

2023-02-23 12:27 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_grpc_client_test.go
> +	api2 "github.com/operator-framework/operator-registry/pkg/api"
maybe registryapi rather than api2?

2023-02-23 12:27 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_grpc_client_test.go
> +	api2 "github.com/operator-framework/operator-registry/pkg/api"
or registry

2023-02-23 12:27 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_grpc_client_test.go
> +	})
might be worth adding error test cases as well

2023-02-23 12:28 UTC, perdasilva commented on pkg/lib/grpc/grpc.go
> +package grpc
doesn't need to be in this PR, but I think we should open a ticket and move all of this to the registry repo. It seems like it could be useful beyond this use-case

2023-02-23 12:29 UTC, perdasilva commented on pkg/lib/grpc/grpc.go
> +func grpcProxyURL(addr string) (*url.URL, error) {
I feel like I've seen this code before. Is it from the olm repo? if we move this to operator-registry we should also update olm.

2023-02-23 12:31 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_cache_querier_test.go
> +	var querier input.EntitySource
maybe just make it a straigh up RegistryCacheQuerier so you don't need to cast it back in the AfterEach?

2023-02-23 12:33 UTC, perdasilva commented on pkg/deppy/input/catalogsource/registry_bundle_to_entity_test.go
> +	It("generates entity from bundle", func() {
you may want to also poke at some of the error cases

2023-02-23 12:35 UTC, perdasilva requested changes
Looks really good and like you've put a lot of effort into this. Thank you!
I think we should move all of this code to the `operator-controller` and remove the dependencies on olm and registry from deppy.
I've left a few comments that I hope will help ^^ Please let me know if you need any help or have any questions =D

2023-03-29 21:05 UTC, ankitathomas commented
Closing in favor of https://github.com/operator-framework/operator-controller/pull/129

2023-03-29 21:05 UTC, closed without merging